// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DiamondShopSystem.Data.Models;

public partial class Product
{
    public int ProductId { get; set; }

    public int? CategoryId { get; set; }

    public string Tital { get; set; }

    public string Image { get; set; }

    public string Code { get; set; }

    public int? Amount { get; set; }

    public string Description { get; set; }

    public virtual Category Category { get; set; }
}